#ifndef ABRECORDTOKENIZER_GLOBAL_H
#define ABRECORDTOKENIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ABRECORDTOKENIZER_LIBRARY)
#  define ABRECORDTOKENIZER_EXPORT Q_DECL_EXPORT
#else
#  define ABRECORDTOKENIZER_EXPORT Q_DECL_IMPORT
#endif

#endif // ABRECORDTOKENIZER_GLOBAL_H
