#ifndef ASERVICEMESSAGEPIPE_GLOBAL_H
#define ASERVICEMESSAGEPIPE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASERVICEMESSAGEPIPE_LIBRARY)
#  define ASERVICEMESSAGEPIPE_EXPORT Q_DECL_EXPORT
#else
#  define ASERVICEMESSAGEPIPE_EXPORT Q_DECL_IMPORT
#endif

#endif // ASERVICEMESSAGEPIPE_GLOBAL_H
